import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import io
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from category_encoders import TargetEncoder

def optimizar_dataframe(df):
    """Optimiza los tipos de datos de un DataFrame para reducir el uso de memoria y disco."""
    print("   -> Optimizando tipos de datos del DataFrame...")
    for col in df.columns:
        if df[col].dtype == 'object' or pd.api.types.is_categorical_dtype(df[col]):
            if len(df[col].unique()) / len(df[col]) < 0.5:
                df[col] = df[col].astype('category')
        elif df[col].dtype.kind in 'if':
            df[col] = pd.to_numeric(df[col], downcast='integer')
            df[col] = pd.to_numeric(df[col], downcast='float')
    print("   -> Optimización completada.")
    return df

def cargar_y_procesar_datos():
    """Carga y procesa completamente los datos desde el archivo Excel."""
    try:
        print("Paso 1/3: Cargando y procesando datos desde Excel...")
        ruta_archivo = "Acumulado Ventas 18-24.xlsx"
        required_columns = ['MARCA', 'MODELO', 'VERSION', 'AÑO', 'MODELOT', 'Combustible', 'CONDICION DE VENTA', 'FECHA DE INGRESO', 'FECHA DE PAGO', 'NUMERO DE SUBASTAS', 'NUMERO DE OFERTAS', 'PRECIO RESERVA', 'CANTIDAD OFERTADA', 'COSTO CLIENTE', 'PRECIO DE MERCADO', 'ORIGEN', 'PROPIETARIO', 'FECHA DE SUBASTA']
        df_ventas_source = pd.read_excel(ruta_archivo, usecols=required_columns)
        df_ventas_source.columns = df_ventas_source.columns.str.strip().str.replace(" ", "_").str.upper()

        # --- Transformaciones ---
        reparar_list = ["ASEGURADORA PARA REPARAR", "SEMINUEVO (NO SINIESTRADO)", "ASEGURADORA DESTACADO", "ENTREGAR A BENEFICIARIO", "SIN ASIGNAR"]
        df_ventas_source['CLASIFICACION_VENTA'] = np.where(df_ventas_source['CONDICION_DE_VENTA'].isin(reparar_list), "REPARAR", "CHATARRIZAR")
        conditions_modelo = [df_ventas_source['MODELOT'].isin(["SEDAN", "HATCH BACK", "PICK UP"]), df_ventas_source['MODELOT'] == "MOTO"]
        choices_modelo = ["AUTO", "MOTO"]
        df_ventas_source['CLASIFICACION_MODELO'] = np.select(conditions_modelo, choices_modelo, default='E. PESADO')
        marcas_chinas = ["BAIC", "JMC", "CHANGAN", "DFSK", "JAC", "SERES", "MG", "CHIREY", "OMODA", "JAECOO", "JETOUR", "BYD", "SEV", "HAVAL", "ORA", "TANK", "GEELY", "ZEEKR", "GAC", "NETA", "BESTUNE", "FAW", "WEY", "KIRI", "IM", "EXCEED", "BAOJUN", "DENZA", "FENGON", "GEOMETRY"]
        marcas_chinas_upper = [marca.upper() for marca in marcas_chinas]
        df_ventas_source['ORIGEN_MARCA'] = np.where(df_ventas_source['MARCA'].str.strip().str.upper().isin(marcas_chinas_upper), "CHINO", "GENERAL")
        
        data_referencia = """CLIENTE	GROUP	SEGMENTO
7-ELEVEN MEXICO SA DE CV	7-ELEVEN MEXICO SA DE CV	SEMINUEVOS
A.N.A. COMPAÑIA DE SEGUROS	ANA COMPAÑÍA DE SEGUROS	SALVAMENTOS
ADMINISTRACIÓN VENTURA SA DE CV	ADMINISTRACIÓN VENTURA SA DE CV	SEMINUEVOS
AFORE XXI BANORTE S.A DE C.V	AFORE XXI BANORTE S.A DE C.V	SEMINUEVOS
AGRICULTURA NACIONAL	GRUPO DRAGON	SEMINUEVOS
AIG SEGUROS MEXICO	AIG	SEMINUEVOS
ALD AUTOMOTIVE, S.A. DE C.V	ALD AUTOMOTIVE, S.A. DE C.V	SEMINUEVOS
ALLIANZ MEXICO SA COMPAÑIA DE SEGUROS	ALLIANZ MEXICO SA COMPAÑIA DE SEGUROS	SEMINUEVOS
ANA COMPAÑIA DE SEGUROS	ANA COMPAÑÍA DE SEGUROS	SALVAMENTOS
ANA COMPAÑÍA DE SEGUROS	ANA COMPAÑÍA DE SEGUROS	SALVAMENTOS
ARIMECHU SC	ARIMECHU SC	SEMINUEVOS
ARIZA DE MEXICO SA DECV	ARIZA DE MEXICO SA DECV	SEMINUEVOS
ARRENDADORA ACTIVER SA DE CV	ACTINVER	SEMINUEVOS
ASEGURADORA B	ASEGURADORA B	SALVAMENTOS
AUTOS Y SALVAMENTOS, S.A. DE C.V.	AUTOS Y SALVAMENTOS, S.A. DE C.V.	SALVAMENTOS
AUTOTRANSPORTES DE DISTRIBUCION Y CONSOLIDACION	ESTAFETA	SEMINUEVOS
AXA DESTACADOS	AXA SEGUROS S.A. DE C.V.	SALVAMENTOS
AXA SEGUROS	AXA SEGUROS S.A. DE C.V.	SALVAMENTOS
AXA SEGUROS S.A. DE C.V.	AXA SEGUROS S.A. DE C.V.	SALVAMENTOS
BALA EXPRESS S.A DE C.V	BALA EXPRESS S.A DE C.V	SEMINUEVOS
BANCO AHORRO FAMSA S.A INSTITUCION DE BANCA MULTIPLE EN LIQUIDACION	BAFAMSA	SEMINUEVOS
BANCO AHORRO FAMSA S.A.	BAFAMSA	SEMINUEVOS
BANCO AHORRO FAMSA S.A. INSTITUCION DE BANCA MULTIPLE EN LIQUIDACION	BAFAMSA	SEMINUEVOS
BANCO AZTECA, S.A. INSTITUCIÓN DE BANCA MULTIPLE	BANCO AZTECA, S.A. INSTITUCIÓN DE BANCA MULTIPLE	SEMINUEVOS
BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BANCA MULTIPLE GRUPO FINANCIERO BANORTE	BANCO MERCANTIL DEL NORTE, S. A. (BANORTE)	SEMINUEVOS
BANCO MERCANTIL DEL NORTE, S. A. (BANORTE)	BANCO MERCANTIL DEL NORTE, S. A. (BANORTE)	SEMINUEVOS
BBVA LEASING MEXICO SA DE CV	BBVA LEASING MEXICO SA DE CV	SEMINUEVOS
BDF CORPORATIVO SA DE CV	BDF CORPORATIVO SA DE CV	SEMINUEVOS
BERRYMEX	BERRYMEX S DE RL DE CV	SEMINUEVOS
BERRYMEX S DE RL DE CV	BERRYMEX S DE RL DE CV	SEMINUEVOS
BINARIO DEL NORTE	BINARIO DEL NORTE	SEMINUEVOS
BMW FINANCIAL SERVICES DE MEXICO SA DE CV SOFOM ENR	BMW FINANCIAL SERVICES DE MEXICO SA DE CV SOFOM ENR	SEMINUEVOS
BMW LEASING DE MEXICO SA DE CV	BMW LEASING DE MEXICO SA DE CV	SEMINUEVOS
CA FINANCIAL SERVICES SAPI DE CV	CA FINANCIAL SERVICES SAPI DE CV	SEMINUEVOS
CA SOLUCIONES FINANCIERAS SA DE CV	CA SOLUCIONES FINANCIERAS SA DE CV	SEMINUEVOS
CALIDAD EN RECURSOS Y SERVICIO SA DE CV (CARSSA)	CALIDAD EN RECURSOS Y SERVICIO SA DE CV (CARSSA)	SEMINUEVOS
CASANOVA CHAPULTEPEC SA DE CV	CASANOVA	SEMINUEVOS
CASANOVA RENT SA DE CV	CASANOVA	SEMINUEVOS
CASANOVA VALLEJO SA DE CV	CASANOVA	SEMINUEVOS
CASANOVA VOLKS SA DE CV	CASANOVA	SEMINUEVOS
CHUBB SEGUROS MEXICO SA	CHUBB	SALVAMENTOS
CHUBB SEGUROS MEXICO	CHUBB	SALVAMENTOS
CHUBB SEGUROS MEXICO SA DESTACADOS	CHUBB	SALVAMENTOS
CHUBB UTILITARIOS	CHUBB	SALVAMENTOS
COMBAND DTH, S DE RL DE CV	DISH	SEMINUEVOS
COMERCIALIZADORA DE FRECUENCIAS SATELITALES,S. DE R.L. DE C.V.	DISH	SEMINUEVOS
COMERCIALIZADORA DE LACTEOS Y DERIVADOS	LALA	SEMINUEVOS
COMERCIALIZADORA DE LÁCTEOS Y DERIVADOS SA DE CV	LALA	SEMINUEVOS
COMERCIALIZADORA PEPSICO MEXICO	PEPSICO	SEMINUEVOS
COMERCIALIZADORA PEPSICO MEXICO DIVERSOS	PEPSICO	SEMINUEVOS
COMERCIALIZADora PEPSICO MEXICO S DE RL DE CV	PEPSICO	SEMINUEVOS
CONAUTO	CONAUTO	SEMINUEVOS
CONFITERIA ALEGRO	PEPSICO	SEMINUEVOS
CONFITERIA ALEGRO S DE RL DE CV	PEPSICO	SEMINUEVOS
CONTROLADORA VENTURA SA DE CV	CONTROLADora VENTURA SA DE CV	SEMINUEVOS
CORPORATIVO GAVIOTAS SALVAMENTOS, S.A. DE C.V.	CORPORATIVO GAVIOTAS	SEMINUEVOS
CORPORATIVO GAVIOTAS, S.A. DE C.V.	CORPORATIVO GAVIOTAS	SEMINUEVOS
CUENCA DEL PLATA HOLDING SA DE CV	CUENCA DEL PLATA HOLDING SA DE CV	SEMINUEVOS
CUSTODIAS NESTLE	ELEMENT	SEMINUEVOS
CUSTODIAS-ELEMENT	ELEMENT	SEMINUEVOS
DHL EXPRESS MEXICO	DHL	SEMINUEVOS
DHL EXPRESS MEXICO S.A. DE C.V.	DHL	SEMINUEVOS
DHL SERVICIOS SA DE CV	DHL	SEMINUEVOS
DM SERVICIO INMEDIATO S DE RL DE CV	DISH	SEMINUEVOS
EDGEWELL PERSONAL CARE MEXICO SA DE CV	EDGEWELL PERSONAL CARE MEXICO SA DE CV	SEMINUEVOS
EL AGUILA COMPAÑIA DE SEGUROS	EL AGUILA COMPAÑIA DE SEGUROS	SALVAMENTOS
EL AGUILA DESTACADOS	EL AGUILA COMPAÑIA DE SEGUROS	SALVAMENTOS
ELEMENT FLEET MANAGEMENT CORPORATION MEXICO SA DE CV	ELEMENT	SEMINUEVOS
ENDOFLET	ENDOFLET	SEMINUEVOS
ENERGIZER MEXICO, S. DE R.L. DE C.V.	ENERGIZER MEXICO, S. DE R.L. DE C.V.	SEMINUEVOS
ENERGIZER SERVICES MEXICO S DE RL DE CV	ENERGIZER SERVICES MEXICO S DE RL DE CV	SEMINUEVOS
ESTAFETA CARGA AÉREA	ESTAFETA	SEMINUEVOS
ESTAFETA MEXICANA, S.A. DE C.V.	ESTAFETA	SEMINUEVOS
ESTAFETA SERVICIOS DE APOYO	ESTAFETA	SEMINUEVOS
ESTAFETA SERVICIOS DE APOYO, S.A. DE C.V.	ESTAFETA	SEMINUEVOS
ESTAFETA SOLUCIONES LOGISTICAS S.A. DE C.V.	ESTAFETA	SEMINUEVOS
FEMSA	FEMSA	SEMINUEVOS
FINANCIERA AUTOPCION	FINANCIERA AUTOPCION	SEMINUEVOS
FINVIVIR	FINVIVIR	SEMINUEVOS
FRAMAR DEL GOLFO, S DE RL DE MI	FRAMAR DEL GOLFO, S DE RL DE MI	SEMINUEVOS
FRANCISCO JAVIER RODRIGUEZ GUERRERO	FRANCISCO JAVIER RODRIGUEZ GUERRERO	SEMINUEVOS
GAMESA	PEPSICO	SEMINUEVOS
GAMESA S DE RL DE CV	PEPSICO	SEMINUEVOS
GE/ELEMENT	ELEMENT	SEMINUEVOS
GENERAL DE SEGUROS S.A.B.	GENERAL DE SEGUROS	SALVAMENTOS
GLAFASA SA DE CV	GLAFASA SA DE CV	SEMINUEVOS
GLOBAL MOTORS LEASING	GLOBAL MOTORS LEASING S.A DE C.V.	SEMINUEVOS
GLOBAL MOTORS LEASING S.A DE C.V.	GLOBAL MOTORS LEASING S.A DE C.V.	SEMINUEVOS
GM FINANCIAL DE MEXICO PERSONAS FISICAS	GM FINANCIAL DE MEXICO PERSONAS FISICAS	SEMINUEVOS
GM FINANCIAL DE MÉXICO, S.A. DE C.V. SOFOM ER	GM FINANCIAL DE MÉXICO, S.A. DE C.V. SOFOM ER	SEMINUEVOS
GRUPO DRAGON	GRUPO DRAGON	SEMINUEVOS
GRUPO EMPRESARIAL GONDEL MEXICO SA DE CV	GRUPO EMPRESARIAL GONDEL MEXICO SA DE CV	SEMINUEVOS
GRUPO GAMESA	PEPSICO	SEMINUEVOS
GRUPO GAMESA S DE RL DE CV	PEPSICO	SEMINUEVOS
GRUPO SABRITAS S DE R L DE CV	PEPSICO	SEMINUEVOS
GRUPO SALINAS	GRUPO SALINAS	SEMINUEVOS
HDI DESTACADOS	HDI SEGUROS S.A. DE C.V.	SALVAMENTOS
HDI SEGUROS	HDI SEGUROS S.H. DE C.V.	SALVAMENTOS
HDI SEGUROS S.A. DE C.V.	HDI SEGUROS S.A. DE C.V.	SALVAMENTOS
HDM SEGUROS S.A. DE C.V.	HDM SEGUROS S.A. DE C.V.	SALVAMENTOS
IMPULSORA SAHUAYO, S.A. DE C.V.	IMPULSORA SAHUAYO, S.A. DE C.V.	SEMINUEVOS
INFRAESTRUCTURA ENERGETICA NOVA	IENOVA	SEMINUEVOS
INFRAESTRUCTURA ENERGÉTICA NOVA, S.A.B. DE C.V.	IENOVA	SEMINUEVOS
JHONSON & JHONSON SA DE CV	JHONSON & JHONSON SA DE CV	SEMINUEVOS
LA LATINOAMERICANA SEGUROS	LA LATINOAMERICana SEGUROS, S.A	SALVAMENTOS
LA LATINOAMERICANA SEGUROS, S.A	LA LATINOAMERICANA SEGUROS, S.A	SALVAMENTOS
LACTOPRODUCTO LA LOMA SA DE CV	LALA	SEMINUEVOS
LACTOPRODUCTOS LA LOMA	LALA	SEMINUEVOS
LEASEPLAN MEXICO	LEASEPLAN MEXICO SA DE CV	SEMINUEVOS
LEASEPLAN MEXICO SA DE CV	LEASEPLAN MEXICO SA DE CV	SEMINUEVOS
LUMO FINANCIERA DEL CENTRO, S.A. DE C.V.	LUMO FINANCIERA DEL CENTRO, S.A. DE C.V.	SEMINUEVOS
MARYKAY-ELEMENT	ELEMENT	SEMINUEVOS
MENSAJERIA METROPOLITANA, S.A. DE C.V	ESTAFETA	SEMINUEVOS
MEXICANA DE LUBRICANTES	MEXICANA DE LUBRICANTES SA DE CV	SEMINUEVOS
MEXICANA DE LUBRICANTES SA DE CV	MEXICANA DE LUBRICANTES SA DE CV	SEMINUEVOS
MONARCA BERRIES	MONARCA BERRIES	SEMINUEVOS
NAZRE HASSAM ASSAD JACQUES	NAZRE HASSAM ASSAD JACQUES	SEMINUEVOS
NESTLÉ DE MÉXICO S.A. DE C.V.	ELEMENT	SEMINUEVOS
NESTLÉ SERVICIOS CORPORATIVOS S.A. DE C.V.	NESTLÉ SERVICIOS CORPORATIVOS S.A. DE C.V.	SEMINUEVOS
OFICINA COORDINADORA DE RIESGOS ASEGURADOS, S.C.	OFICINA COORDINADORA DE RIESGOS ASEGURADOS, S.C.	SEMINUEVOS
OPERADORA FMA	FMA	SEMINUEVOS
PEPSICO INTERNACIONAL MEXICO	PEPSICO	SEMINUEVOS
PEPSICO INTERNACIONAL MEXICO S DE RL DE CV	PEPSICO	SEMINUEVOS
PEPSICO NV	PEPSICO NV	SEMINUEVOS
PERSONNA INTERNATIONAL DE MEXICO SA DE CV	PERSONNA INTERNATIONAL DE MEXICO SA DE CV	SEMINUEVOS
POCHTECA MATERIAS PRIMAS	POCHTECA MATERias PRIMAS	SEMINUEVOS
PRESEA TELEVISION S. DE RL DE CV	DISH	SEMINUEVOS
PRESTAMOS AUTO EFECTIVO	PRESTAMOS AUTO EFECTIVO	SEMINUEVOS
PRIMERO SEGUROS	PRIMERO SEGUROS SA DE CV	SALVAMENTOS
PRIMERO SEGUROS SA DE CV	PRIMERO SEGUROS SA DE CV	SALVAMENTOS
QUALITAS COMPAÑÍA DE SEGUROS S.A. DE C.V.	QUALITAS COMPAÑÍA DE SEGUROS S.A. DE C.V.	SALVAMENTOS
QUÁLITAS DIVERSOS	QUALITAS COMPAÑÍA DE SEGUROS S.A. DE C.V.	SALVAMENTOS
REFERIDOS EOL	REFERIDOS EOL	SEMINUEVOS
REPARTOS RAPIDOS DE COLIMA, S. A. DE C. V.	REPARTOS RAPIDOS DE COLIMA, S. A. DE C. V.	SEMINUEVOS
REPARTOS RAPIDOS DE MICHOACAN, S. A. DE C.V.	REPARTOS RAPIDOS DE MICHOACAN, S. A. DE C.V.	SEMINUEVOS
REPARTOS RAPIDOS DE SINALOA SA DE CV	REPARTOS RAPIDOS DE SINALOA SA DE CV	SEMINUEVOS
REPARTOS RAPIDOS DEL BAJIO	REPARTOS RAPIDOS DEL BAJIO	SEMINUEVOS
REPARTOS RAPIDOS DEL NAYAR, S. A. DE C. V.	REPARTOS RAPIDOS DEL NAYAR, S. A. DE C. V.	SEMINUEVOS
REPARTOS RAPIDOS JALISCO, S.A. DE C. V.	REPARTOS RAPIDOS JALISCO, S.A. DE C. V.	SEMINUEVOS
REPARTOS RAPIDOS SA DE CV	REPARTOS RAPIDOS SA DE CV	SEMINUEVOS
ROGUER DEL SUR DE TAMAULIPAS S DE RL MI	ROGUER DEL SUR DE TAMAULIPAS S DE RL MI	SEMINUEVOS
RYDER CAPITAL, S. DE R.L DE C.V	RYDER CAPITAL, S. DE R.L DE C.V	SEMINUEVOS
SABRITAS	PEPSICO	SEMINUEVOS
SABRITAS S DE RL DE CV	PEPSICO	SEMINUEVOS
SEGUROS AFIRME, S.A. DE C.V.	SEGUROS AFIRME, S.A. DE C.V.	SALVAMENTOS
SEGUROS ATLAS	SEGUROS ATLAS, S. A.	SALVAMENTOS
SEGUROS ATLAS, S. A.	SEGUROS ATLAS, S. A.	SALVAMENTOS
SEGUROS AZTECA	SEGUROS AZTECA	SALVAMENTOS
SEGUROS AZTECA DAÑOS	SEGUROS AZTECA	SALVAMENTOS
SEGUROS BANORTE SA DE CV GRUPO FINANCIERO BANORTE	BANORTE	SALVAMENTOS
SEGUROS EL POTOSI	SEGUROS EL POTOSI S.A.	SALVAMENTOS
SEGUROS EL POTOSI S.A.	SEGUROS EL POTOSI S.A.	SALVAMENTOS
SEGUROS MULTIVA S.A. GRUPO FINANCIERO MULTIVA	SEGUROS MULTIVA S.A.	SALVAMENTOS
SERCORP DM S DE RL DE CV	DISH	SEMINUEVOS
SEVEN ELEVEN	SEVEN ELEVEN	SEMINUEVOS
SICREA COMERCIAL S.A. DE C.V.	SICREA	SEMINUEVOS
SINIESTROS DIVERSOS	SEGUROS BANORTE GENERALI	SALVAMENTOS
SISTEMA DE CREDITO AUTOMOTRIZ	SICREA	SEMINUEVOS
SISTEMA DE CREDITO AUTOMOTRIZ S.A. DE C.V.	SICREA	SEMINUEVOS
SOCIEDAD AUTOMOTRIZ LEGA	SOCIEDAD AUTOMOTRIZ LEGA S.A. DE C.V.	SEMINUEVOS
SOCIEDAD AUTOMOTRIZ LEGA S.A. DE C.V.	SOCIEDAD AUTOMOTRIZ LEGA S.A. DE C.V.	SEMINUEVOS
SOLUFI	SOLUFI	SEMINUEVOS
SUBASTAS VENTURA S.A. DE C.V.	SUBASTAS VENTURA S.A. DE C.V.	SEMINUEVOS
SURTIDORA DE TRACTOCAMIONES Y REFACCIONES SA DE CV	SURTIDora DE TRACTOCAMIONES Y REFACCIONES SA DE CV	SEMINUEVOS
SV CHATARRA	SV CHATARRA	SEMINUEVOS
TRANSLOGISTICA	ESTAFETA	SEMINUEVOS
TRANSPORTADORA TERRESTRE	ESTAFETA	SEMINUEVOS
TRANSPORTES ESPECIALIZADOS OLEAGINOSA GRANOS Y ALIMENTO BALANCEADO	AVIGRUPO	SEMINUEVOS
TRANSPORTES UNIDOS CASTAÑEDA S A P I DE CV	TRANSPORTES UNIDOS CASTAÑEDA S A P I DE CV	SEMINUEVOS
TRANSPORTES VALBO Y ASOCIADOS	VALBO	SEMINUEVOS
TURISMO GARGO SA DE CV	TURISMO GARGO SA DE CV	SEMINUEVOS
UNIFIN FINANCIERA	UNIFIN FINANCIERA	SEMINUEVOS
UTILITARIOS BANORTE	BANORTE	SALVAMENTOS
UTILITARIOS CHUBB	CHUBB	SALVAMENTOS
VALUE ARRENDADORA SA DE CV SOFOM ER VALUE GRUPO FINANCIERO	VALUE	SEMINUEVOS
VALUE AUTOMOTRIZ	VALUE	SEMINUEVOS
VENTAS PARTICULARES	VENTAS PARTICULARES	SEMINUEVOS
VENTURA EMPEÑOS	VENTURA EMPEÑOS	SEMINUEVOS
VIAL ASSIST	VIAL ASSIST	SEMINUEVOS
ZURICH ASEGURADORA MEXICana	ZURICH ASEGURADORA MEXICana	SALVAMENTOS
ZURICH DAÑOS	ZURICH ASEGURADORA MEXICana	SALVAMENTOS
MENSAJERIA METROPOLITANA	ESTAFETA	SEMINUEVOS
LUMO FINANCIERA DEL CENTRO	LUMO FINANCIERA DEL CENTRO, S.A. DE C.V.	SEMINUEVOS
ESTAFETA SOLUCIONES LOGISTICAS	ESTAFETA	SEMINUEVOS
GRUPO SABRITAS	PEPSICO	SEMINUEVOS
BALA EXPRESS	BALA EXPRESS S.A DE C.V	SEMINUEVOS
DM SERVICIO INMEDIATO	DISH	SEMINUEVOS
SERCORP DM	DISH	SEMINUEVOS
PRESEA TELEVISION	DISH	SEMINUEVOS
COMERCIALIZADORA DE FRECUENCIAS SATELITALES	DISH	SEMINUEVOS
123LEASE	GRUPO PIRAMIDE	SEMINUEVOS
GC CONAUTOPCIÓN, S.A. DE C.V.	CONAUTO	SEMINUEVOS
FINANCIERA POR EL IMPULSO ECONOMICO S.A.DEC.V., SOFOM,E.N.R.	FINANCIERA POR EL IMPULSO ECONOMICO S.A.DEC.V., SOFOM,E.N.R.	SEMINUEVOS
"""
        # --- CORRECCIÓN APLICADA AQUÍ ---
        # Se cambia el separador a '\t' (tabulador) para que pandas lea las columnas correctamente.
        df_referencia = pd.read_csv(io.StringIO(data_referencia), sep='\t', engine='python')
        
        df_referencia.rename(columns={'GROUP': 'GRUPO'}, inplace=True)
        df_referencia['CLIENTE'] = df_referencia['CLIENTE'].str.strip().str.upper()
        df_referencia['GRUPO'] = df_referencia['GRUPO'].str.strip().str.upper()
        df_referencia['SEGMENTO'] = df_referencia['SEGMENTO'].str.strip().str.upper()
        df_ventas_source['PROPIETARIO'] = df_ventas_source['PROPIETARIO'].astype(str).str.strip().str.upper()
        
        df_full = pd.merge(df_ventas_source, df_referencia, left_on='PROPIETARIO', right_on='CLIENTE', how='left')
        df_full['CLIENTE'] = df_full['GRUPO']
        df_full['CLIENTE'].fillna(df_full['PROPIETARIO'], inplace=True)
        df_full['SEGMENTO'].fillna("SEMINUEVOS", inplace=True) # <-- MODIFICACIÓN REALIZADA AQUÍ
        df_full.drop(columns=['GRUPO'], inplace=True)

        df_full['FECHA_DE_INGRESO'] = pd.to_datetime(df_full['FECHA_DE_INGRESO'], errors='coerce')
        df_full['FECHA_DE_PAGO'] = pd.to_datetime(df_full['FECHA_DE_PAGO'], errors='coerce')
        df_full['FECHA_DE_SUBASTA'] = pd.to_datetime(df_full['FECHA_DE_SUBASTA'], errors='coerce')
        df_full.dropna(subset=['FECHA_DE_PAGO', 'FECHA_DE_SUBASTA'], inplace=True) 
        df_full['DIAS_HABILES_VENTA'] = df_full.apply(lambda row: np.busday_count(row['FECHA_DE_INGRESO'].date(), row['FECHA_DE_PAGO'].date()) if pd.notna(row['FECHA_DE_INGRESO']) and pd.notna(row['FECHA_DE_PAGO']) else np.nan, axis=1)
        df_full['AÑO_SUBASTA'] = df_full['FECHA_DE_SUBASTA'].dt.year
        df_full['MES_SUBASTA'] = df_full['FECHA_DE_SUBASTA'].dt.month
        df_full['RECUPERACION_PRECIO'] = (df_full['CANTIDAD_OFERTADA'] / df_full['COSTO_CLIENTE']).replace([np.inf, -np.inf], np.nan)
        df_full['RECUPERACION_VALOR'] = (df_full['CANTIDAD_OFERTADA'] / df_full['PRECIO_DE_MERCADO']).replace([np.inf, -np.inf], np.nan)
        print("   -> Procesamiento completado.")
        
        return df_full
    except Exception as e:
        print(f"Error: {e}")
        return None

def entrenar_y_guardar_modelos(df_full):
    print("Paso 2/3: Entrenando y guardando modelos...")
    
    historical_stats = df_full.groupby(['MARCA', 'MODELO', 'VERSION']).agg(PRECIO_HISTORICO_MINIMO=('CANTIDAD_OFERTADA', 'min'), PRECIO_HISTORICO_PROMEDIO=('CANTIDAD_OFERTADA', 'mean'), PRECIO_HISTORICO_MAXIMO=('CANTIDAD_OFERTADA', 'max'), PRECIO_HISTORICO_MODA=('CANTIDAD_OFERTADA', lambda x: x.mode().iloc[0] if not x.value_counts().empty and x.value_counts().iloc[0] > 1 else x.median()), CONTEO_REGISTROS_HISTORICOS=('CANTIDAD_OFERTADA', 'count'), PROMEDIO_OFERTAS_HISTORICO=('NUMERO_DE_OFERTAS', 'mean'), PROMEDIO_SUBASTAS_HISTORICO=('NUMERO_DE_SUBASTAS', 'mean'), PROMEDIO_COSTO_CLIENTE=('COSTO_CLIENTE', 'mean'), TIEMPO_VENTA_PROMEDIO_DIAS=('DIAS_HABILES_VENTA', 'mean')).reset_index()
    df_full = pd.merge(df_full, historical_stats, on=['MARCA', 'MODELO', 'VERSION'], how='left')
    
    columnas_a_quitar = ['CANTIDAD_OFERTADA', 'DIAS_HABILES_VENTA', 'RECUPERACION_PRECIO', 'NUMERO_DE_OFERTAS', 'RECUPERACION_VALOR', 'FECHA_DE_INGRESO', 'FECHA_DE_PAGO', 'FECHA_DE_SUBASTA', 'ORIGEN', 'PROPIETARIO', 'MODELOT', 'CONDICION_DE_VENTA', 'AÑO_SUBASTA', 'MES_SUBASTA']
    feature_cols = [col for col in df_full.columns if col not in columnas_a_quitar]
    df_full.dropna(subset=feature_cols + ['CANTIDAD_OFERTADA', 'DIAS_HABILES_VENTA', 'RECUPERACION_PRECIO', 'NUMERO_DE_OFERTAS'], inplace=True)
    
    X = df_full[feature_cols].copy()
    y_precio = df_full['CANTIDAD_OFERTADA']
    y_dias = df_full['DIAS_HABILES_VENTA']
    y_recuperacion = df_full['RECUPERACION_PRECIO']
    y_ofertas = df_full['NUMERO_DE_OFERTAS']
    
    columnas_categoricas_target = ['MARCA', 'MODELO', 'VERSION']
    columnas_categoricas_onehot = ['CLASIFICACION_VENTA', 'CLASIFICACION_MODELO', 'ORIGEN_MARCA', 'CLIENTE', 'SEGMENTO', 'COMBUSTIBLE']
    
    preprocesador = ColumnTransformer(transformers=[('target', TargetEncoder(), columnas_categoricas_target), ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), columnas_categoricas_onehot)], remainder='passthrough')
    
    for col in columnas_categoricas_target + columnas_categoricas_onehot:
        if col in X.columns: X.loc[:, col] = X[col].astype(str).fillna('N/A')

    modelo_precio = Pipeline(steps=[('preprocesador', preprocesador),('regresor', RandomForestRegressor(n_estimators=42, random_state=12, n_jobs=-1))]); modelo_precio.fit(X, y_precio)
    modelo_dias = Pipeline(steps=[('preprocesador', preprocesador),('regresor', RandomForestRegressor(n_estimators=42, random_state=12, n_jobs=-1))]); modelo_dias.fit(X, y_dias)
    modelo_recuperacion = Pipeline(steps=[('preprocesador', preprocesador),('regresor', RandomForestRegressor(n_estimators=27, random_state=8, n_jobs=-1))]); modelo_recuperacion.fit(X, y_recuperacion)
    modelo_ofertas = Pipeline(steps=[('preprocesador', preprocesador),('regresor', RandomForestRegressor(n_estimators=48, random_state=12, n_jobs=-1))]); modelo_ofertas.fit(X, y_ofertas)
    
    joblib.dump(modelo_precio, 'modelo_precio.joblib', compress=3); joblib.dump(modelo_dias, 'modelo_dias.joblib', compress=3); joblib.dump(modelo_recuperacion, 'modelo_recuperacion.joblib', compress=3); joblib.dump(modelo_ofertas, 'modelo_ofertas.joblib', compress=3)
    joblib.dump(feature_cols, 'feature_cols.joblib')
    historical_stats.to_parquet('historical_stats.parquet', index=False)
    
    print("   -> Modelos y archivos de configuración guardados.")

if __name__ == "__main__":
    DATABASE_URL = "postgresql://neondb_owner:npg_Rd1vkhV7oCIg@ep-curly-mountain-ae52d80a-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
    NOMBRE_TABLA = 'ventas_historicas' 
    
    df_full = cargar_y_procesar_datos()
    
    if df_full is not None:
        df_optimizado = optimizar_dataframe(df_full.copy())
        engine = create_engine(DATABASE_URL)
        print(f"Subiendo datos a la tabla '{NOMBRE_TABLA}' en Neon... (Esto puede tardar varios minutos)")
        df_optimizado.to_sql(NOMBRE_TABLA, engine, if_exists='replace', index=False, chunksize=10000)
        print("   -> ¡Datos subidos exitosamente a Neon!")
        
        entrenar_y_guardar_modelos(df_full)
        
        print("Paso 3/3: Creando y guardando las opciones de los filtros...")
        opciones_filtros = {
            'marcas': sorted(df_full['MARCA'].unique()),
            'modelos': sorted(df_full['MODELO'].unique()),
            'condiciones': sorted(df_full['CONDICION_DE_VENTA'].unique()),
            'anios': sorted(df_full['AÑO'].astype(int).unique(), reverse=True),
            'clas_venta': sorted(df_full['CLASIFICACION_VENTA'].unique()),
            'clas_modelo': sorted(df_full['CLASIFICACION_MODELO'].unique()),
            'origen_marca': sorted(df_full['ORIGEN_MARCA'].unique()),
            'clientes': sorted(df_full['CLIENTE'].unique()),
            'segmentos': sorted(df_full['SEGMENTO'].unique()),
            'combustibles': sorted(df_full['COMBUSTIBLE'].astype(str).unique()),
            'anios_subasta': sorted(df_full['AÑO_SUBASTA'].astype(int).unique(), reverse=True),
            'meses': sorted(df_full['MES_SUBASTA'].unique()),
            'modelos_por_marca': df_full.groupby('MARCA')['MODELO'].unique().apply(list).to_dict()
        }
        joblib.dump(opciones_filtros, 'opciones_filtros.joblib')
        print("   -> Archivo 'opciones_filtros.joblib' guardado.")
        
        print("\n¡Proceso de entrenamiento y carga completado!")